### ISSUE TITLE
Docker Hub のイメージにタグをつけてほしい

### ISSUE THREAD

**Issue by inutano** [dbcls/sparqlist#15]
Dockerコンテナが用意してあるので楽にお試しできて最高なのですが、ビルドされたイメージが latest しか用意されておらずプロダクションに使えません… リリースバージョンに倣ったコンテナのタグをつけてほしいです！
https://hub.docker.com/r/dbcls/sparqlist/tags

**Comment by ktym** [comment]
hooks/post_push をつかって、コミットのハッシュで生成するように（しばらく前に）浦嶌さんが対応してくださっていました！
