### ISSUE TITLE
CORS設定

### ISSUE THREAD

**Issue by yamadaissaku** [dbcls/sparqlist#19]
* 以前のバージョンでは、HTTPヘッダは

```
TTP/2 200
server: nginx/1.15.9
date: Wed, 13 May 2020 04:57:14 GMT
content-type: application/json; charset=utf-8
content-length: 791
x-powered-by: Express
access-control-allow-origin: *
etag: W/"317-tjjIakcmZ+qDCM4a/WTNxPsbMqM"
strict-transport-security: max-age=31536000
```
となっており、
`access-control-allow-origin: *`
が出力されていました。

しかし、新しいバージョンのHTTPヘッダは
```
HTTP/2 200
server: nginx/1.17.10
date: Wed, 13 May 2020 06:25:19 GMT
content-type: text/html; charset=UTF-8
content-length: 1692
x-powered-by: Express
accept-ranges: bytes
cache-control: public, max-age=0
last-modified: Tue, 05 May 2020 22:14:17 GMT
etag: W/"69c-171e6e766a8"
strict-transport-security: max-age=31536000
```

であり、CORS問題が発生してしまいました。
これは、変更していただけるのでしょうか？

**Comment by ursm** [comment]
現象を再現できませんでした。
![image](https://user-images.githubusercontent.com/7548/82282380-a9d76600-99ce-11ea-85c3-64a46494b88b.png)
以下3点ご確認いただけますでしょうか。

1. いただいたヘッダのうち Content-Type がそれぞれで異なっているのが気になります。アクセスしているもの自体が別だったりしないでしょうか。
1. nginx を経由せず直接 sparqlist を叩いても同様の挙動になるでしょうか。挙動が変わる場合は nginx によってヘッダが上書きされているのではないかと思います。
1. sparqlist は `/api/:sparqlet_id` へのアクセスにのみ CORS 設定を付与しますが、他のパスにアクセスしていることはないでしょうか。もしそうだとしたら以前は nginx がヘッダを付与していたのが、設定の変更によって付かなくなったのだと思います。

**Comment by yamadaissaku** [comment]
- お返事ありがとうございます。アクセスしているSPARQList自体は、新旧で異なりますが、同じこのリポジトリから利用しているものです。

1. Content-Type がそれぞれで異なっているのは、私も気になりましたが動作自体は旧バージョンで問題なかったです。

2. SAPRQList自体を起動して、apiを実行する分には新旧問題ないようです。APIはJSONを返してくれます。
ちなみに、
* 新環境：https://test.sparqlist.glyconavi.org/sparqlist/
* 旧環境：https://sparqlist.glyconavi.org/
です。
`nginx によってヘッダが上書きされている`は、気になりますので確認します。

3. https://test.sparqlist.glyconavi.org/sparqlist/api/CAN_List_all このような場合も CORS 設定を付与いてくれますでしょうか？

**Comment by ursm** [comment]
新旧試してみました。いずれも問題なく Access-Control-Allow-Origin が付いているように見えますが、いかがでしょうか。

![image](https://user-images.githubusercontent.com/7548/82284257-8b279e00-99d3-11ea-8591-7a14622e47ad.png)
![image](https://user-images.githubusercontent.com/7548/82284267-95499c80-99d3-11ea-829b-bff7d44fbc82.png)

> https://test.sparqlist.glyconavi.org/sparqlist/api/CAN_List_all このような場合も CORS 設定を付与いてくれますでしょうか？

ROOT_PATH を指定した状態ということですね。はい、問題ありません。

**Comment by yamadaissaku** [comment]
* curlでみてみると、
```
$ curl -I https://test.sparqlist.glyconavi.org/sparqlist/api/CarTNaGlycanName?glycan=GD3
HTTP/2 200 
server: nginx/1.17.10
date: Tue, 19 May 2020 04:35:02 GMT
content-type: application/json; charset=utf-8
content-length: 791
x-powered-by: Express
access-control-allow-origin: *
etag: W/"317-tjjIakcmZ+qDCM4a/WTNxPsbMqM"
strict-transport-security: max-age=31536000
 
$ curl -I https://sparqlist.glyconavi.org/sparqlist/api/CarTNaGlycanName?glycan=GD3
HTTP/2 200 
server: nginx/1.15.9
date: Tue, 19 May 2020 04:35:29 GMT
content-type: text/html; charset=UTF-8
content-length: 1518
x-powered-by: Express
accept-ranges: bytes
cache-control: public, max-age=0
last-modified: Fri, 02 Aug 2019 06:57:46 GMT
etag: W/"5ee-16c511ec210"
strict-transport-security: max-age=31536000
```
となってまして、なぜか　HTTPヘッダの結果に再現が取れませんでした。
再度、`nginx によってヘッダが上書きされている`も含めて検討します。

**Comment by ursm** [comment]
なるほど、旧の方は ROOT_PATH の指定がないのですね。URL から `/sparqlist` を抜いてみたら新と同様の結果になりました。

```
$ curl -I https://sparqlist.glyconavi.org/api/CarTNaGlycanName
HTTP/1.1 200 OK
Server: nginx/1.15.9
Date: Tue, 19 May 2020 04:43:26 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 791
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: *
ETag: W/"317-tjjIakcmZ+qDCM4a/WTNxPsbMqM"
Strict-Transport-Security: max-age=31536000
```

https://sparqlist.glyconavi.org/CarTNaGlycanName
この画面の見出しの下に API の URL が出ていますので、わからなくなった場合はこちらをご参照ください。
